module.exports = {
	baseMap: [
"                                                                                ",
"        ╔════╗              ╔════╗       With the ROGUE program gone,           ",
"        ║    ║              ║    ║       balance returned to the system.        ",
"        ║    ╠══════════════╣    ║                                              ",
"        ║    ║     ..*..    ║    ║       All characters rejoiced and a          ",
"        ╚═╦══╝     .....    ╚══╦═╝       great celebration was organized.       ",
"          ║      % .....  %    ║                                                ",
"          ║        .....       ║         Some of them are still waiting         ",
"          ║    %   .....       ║         for root to return one day,            ",
"          ║        .....    %  ║                                                ",
"          ║        .....       ║         while others are content with          ",
"          ║  %   % .....       ║         just continuing living their           ",
"          ║        .....   %   ║         infinite virtual existence.            ",
"          ║        .....       ║                                                ",
"          ║ %      ..... %   % ║                                                ",
"          ║      % .....       ║         Still... deep inside... you know       ",
"        ╔═╩══╗     .....  % ╔══╩═╗       the system is doomed to shut down      ",
"        ║    ║     .....    ║    ║       any time.                              ",
"        ║    ╠══════════════╣    ║                                              ",
"        ║    ║              ║    ║       The best you can do is enjoy the       ",
"        ╚════╝              ╚════╝       moment.             --- THE END        ",
"                                                                                "
	],
	exits: [{to: "processMan"}],
	hints: [
		"Thank you for freeing us, you are my hero!",
		"The Rogue program is gone.",
		"Thank you for freeing us, you are my hero!",
		"Thank you for freeing us, you are my hero!",
		"The Rogue program is gone.",
		"Thank you for freeing us, you are my hero!",
		"The Rogue program is gone.",
		"The Rogue program is gone.",
		"Thank you for freeing us, you are my hero!",
		"The Rogue program is gone.",
	],
	welcomeMessage: "You enter the Castle."
}